package Milestone3.common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, READY, PICK, AWAY, SCORE, QUESTION, OPTIONS, CLIENT_ID, RESET_USER_LIST, SYNC_CLIENT, CREATE_ROOM, JOIN_ROOM, GET_ROOMS, PHASE
}
